# Generated by Django 2.0.5 on 2018-05-12 19:44

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_id', models.IntegerField(default=-1)),
                ('img_file', models.ImageField(upload_to=None)),
                ('img_features', picklefield.fields.PickledObjectField(default=0, editable=False)),
                ('img_type', models.CharField(choices=[('dataset', 'dataset'), ('uploaded', 'uploaded')], default='dataset', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MostSimilarImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sim_top_n', picklefield.fields.PickledObjectField(default='', editable=False)),
                ('sim_algo', models.CharField(default='', max_length=100)),
                ('sim_uploaded_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='img_most_sim', to='match.Image')),
            ],
        ),
    ]
